config/routes.rb
DinnerDash::Application.routes.draw do

  resources :visitor_users

  resources :restaurants
  resources :items
  resources :orders
  resources :order_items
  resources :users
  resources :categories
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :charges
  resources :menus
  resources :hours
  resources :restaurant_employees
  resources :locations
  resources :order_restaurants
  root to: 'static_pages#home'

  get "orders/guest_checkout"

  get "approve/:id" => "restaurants#approve", as: 'approve'
  get "restaurant-dashboard/:id" => "restaurants#restaurant_dashboard", as: 'restaurant_dashboard'

  post "items/add_to_order/:id" => 'items#add_to_order', as: 'add_item'
  get "login" => "user_sessions#new"
  get "logout" => "user_sessions#destroy"

  get "checkout" => "orders#checkout", as: 'checkout'
  post "place_order" => "orders#place_order", as: 'place_order'

  #Section for singular checkout
  get "checkout_one" => "orders#checkout_one_restaurant", as: 'checkout_one_restaurant'
  post "place_order_one_restaurant" => "orders#place_order_one_restaurant", as: 'place_order_one_restaurant'


  get "dashboard" => "users#dashboard", as: 'dashboard'

  get "static_pages/home"

  get "past_orders/:unique_url" => "orders#guest_order_receipt", as: "past_orders"

  get "food/:food_type" => "restaurants#load_restaurants_by_type", as: "food_type"
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :orders, as: :customer
  has_many :restaurant_employees
  has_many :restaurants, :through => :restaurant_employees

  validates_presence_of     :password, :on => :create
  validates                 :password, length: { minimum: 6 }
  validates                 :username, length: { in: 2..32 }
  validates_presence_of     :email

  def associate_order(order)
    orders << order
  end

  def change_order_to_completed
    orders.last.update_status("completed")
  end

  def recent_orders
    orders.where(status: 'completed')
  end

  def find_by_email(email)
    User.where(email: email).first
  end

   private


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:new, :create, :edit]
  before_action :require_admin, only: [:index, :dashboard]

  def dashboard
    @items = Item.all.page(params[:page]).per(5)
    @categories = Category.all
    @orders = Order.all.page(params[:page]).per(5)
    @users = User.all.page(params[:page]).per(5)
    @restaurants = Restaurant.all.page(params[:page]).per(5)
    @pending_restaurants = Restaurant.where(status: "pending").page(params[:page]).per(5)
  end

  def index
    @users = User.all
  end

  def show
    @order = current_order
    if current_user.admin
      @user = User.find(params[:id])
    else
      @user = User.find(current_user.id)
    end
    @user_orders = Order.where(user_id: current_user.id)
    if current_user.admin?
      @restaurants = Restaurant.all.page(params[:page]).per(5)
    else
      if current_user.restaurants 
        @restaurants = current_user.restaurants.page(params[:page]).per(5)
      end
    end
  end

  def new
    @user = User.new
  end

  def edit
    if current_user.id != params[:id] && !current_user.admin
      redirect_to user_path(current_user)
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      flash.notice = "User #{@user.username} created!"
      UserMailer.welcome_email(@user).deliver
      redirect_to root_path
    else
      flash[:error] = "There was an error"
      redirect_to new_user_path
    end
  end

  def update
    if @user.update(user_params)
      flash.notice = "User #{@user.username} updated!"
      redirect_to user_path(@user)
    else
      redirect_to edit_user_path
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<%= render 'shared/errors', model:@user %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
   <%= f.submit @user.new_record? ? "Create my account" : "Update my account", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<div id ="dashboard">
  <h2>Admin Dashboard</h2>
  <td>
    <form>
  <%= link_to "Jump To Restaurants",  dashboard_path(:anchor =>"restaurants"), {:class => "btn btn-info"  } %> <br>
  <%= link_to "Jump To Menu Items", dashboard_path(:anchor =>"menu-items"), {:class => "btn btn-info"} %> <br>
  <%= link_to "Jump To Categories List", dashboard_path(:anchor =>"categories-list"), {:class => "btn btn-info"} %> <br>
  <%= link_to "Jump To Orders List", dashboard_path(:anchor =>"orders-list"), {:class => "btn btn-info"} %> <br>
  <%= link_to "Jump To Users List", dashboard_path(:anchor =>"users-list"), {:class => "btn btn-info"} %>
</td>
</form>

  <div class="menu-items">
  <h3>Pending Restaurants</h3>
  <a id="restaurants"></a>
  <% if @pending_restaurants %>
    <% @pending_restaurants.each do |pending| %>
      <div id="<%= pending.url_slug %>">
        <tr>
          <td><%= link_to pending.name, restaurant_path(pending) %> 
          <br>  </td> 
          <td><%= link_to "Accept/Deny Application", approve_path(pending), {:class => "btn btn-success" } %></td>
        </br>     
        </tr>
      </div>
    <% end %>
  <% end %>
      <%= paginate @restaurants %> 
  <div class="menu-items">
  <h3>Menu Items</h3>
  <a id="menu-items"></a>
  <%= link_to "Create New Menu Item", new_item_path, {:class => "btn btn-success create-new-item"} %>
  <br>
  <br>
  <table>
  <% @items.each do |item| %>
    <tr>
      <td><%= link_to item.title, item_path(item.id) %></td>
      <td><%= link_to "Edit", edit_item_path(item.id), {:class => "btn btn-warning edit-item" } %></td>
      <td></td>
    </tr>
  <% end %>
  </table>
  </div>

      <%= paginate @items%>

  <div class="categories-list">
    <h3>Categories</h3>
    <a id="categories-list"></a>
    <%= link_to "Create New Category", new_category_path, {:class => "btn btn-success"} %>
    <br>
    <br>
    <table>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category_path(category.id) %></td>
        <td><%= link_to "Edit", edit_category_path(category.id), {:class=> "btn btn-warning edit-category" } %></td>
      </tr>
      <% end %>
  </div>
  </table>
  <div class="orders-list">
    <h3>Orders</h3>
    <a id="orders-list"></a>
    <%= link_to "Order History", orders_path %>
  </div>
  <%= paginate @orders %>
  <div class="users-list">
    <h3>Users</h3>
    <a id="users-list"></a>
    <table>
     <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user_path(user.id) %></td>
      </tr>
     <% end %>     
   </table>     
  </div>
   <%= paginate @users %>
</div>

app/views/users/edit.html.erb
<h1>Edit your account information</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>All users</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Email</th>
      <th>Admin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Become a New User</h1>
<p>Becoming a user on Craveyard allows you to place your order, view your current order, checkout, and view past orders associated with your account. </p>
<p>Hungry? Sign up today and order out from your favorite menus, all in one place!</p>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <strong>Username:</strong>
  <%= @user.username %>
</h2>
<%= link_to 'Edit Profile', edit_user_path(@user) %>
<br>
  <% if current_user.admin? %>
  <br>
  <%= link_to "Admin Dashboard",  dashboard_path, {:class => "btn btn-info" } %>
  <br>
  <br>
  <%= link_to 'All Users', users_path %>
  <% else %>
  <br>
<%= link_to "Create a New Craveyard Website", new_restaurant_path, {:class => "btn btn-info btn-large" } %>
  <% end %>
<hr>

<% if @restaurants %>
<h2>My Restaurants</h2>
<hr>
  <% @restaurants.each do |restaurant| %>
  <h3><%= link_to restaurant.name, restaurant_dashboard_path(restaurant) %> | <%= restaurant.status %> </h3>
    <% if restaurant.restaurant_detail %>
      <%= restaurant.restaurant_detail.description %>
    <% end %>
    <% if restaurant.restaurant_employees.count > 1 %>
      <% restaurant.restaurant_employees.each do |emp| %>
        <% if emp.user %>
          <%= emp.user.username %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<br>
<%= paginate @restaurants %>
<hr>
<h2>Recent Orders</h2>
<hr>
<div id="recent_orders">
  <% if @user.orders %>
  <% @user.orders.each do |order| %>
    <% if order.not_empty? %>
      <h3>Order Number: <%= order.id %> </h3>
      <p><strong>Date Placed:</strong> <%= order.updated_at.to_s(:long) %></p>
      <p><strong>User:</strong> <%= order.order_username(order.customer_id) %> </p>
      <h5>Order Status: <%= order.status %></h5>
        <table class="table">
          <thead>
            <tr>
              <td>Dish</td>
              <td>Description</td>
              <td>Price</td>
              <td>Quantity</td>
            </tr>
          </thead>
        <% order.items.each do |item| %>
        <tr>
          <% oi = OrderItem.where(order_id: order.id, item_id: item.id).first %>
          <td><%= link_to item.title, item_path(item.id) %></td>
          <td><%= item.description %></td>
          <td><%= print_price(item.price) %></td>
          <td> <%= oi.quantity %></td>
        </tr>
        <% end %>
        <tr>
          <td></td>
          <td><h4>Order Total:</h4></td>
          <td><h4><%= print_price(order.subtotal) %></h4></td>
          <td></td>
        </tr>
        </table>
        <hr>
      <% end %>
    <% end %>
  <% end %>
</div>