config/routes.rb
DinnerDash::Application.routes.draw do

  resources :visitor_users

  resources :restaurants
  resources :items
  resources :orders
  resources :order_items
  resources :users
  resources :categories
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :charges
  resources :menus
  resources :hours
  resources :restaurant_employees
  resources :locations
  resources :order_restaurants
  root to: 'static_pages#home'

  get "orders/guest_checkout"

  get "approve/:id" => "restaurants#approve", as: 'approve'
  get "restaurant-dashboard/:id" => "restaurants#restaurant_dashboard", as: 'restaurant_dashboard'

  post "items/add_to_order/:id" => 'items#add_to_order', as: 'add_item'
  get "login" => "user_sessions#new"
  get "logout" => "user_sessions#destroy"

  get "checkout" => "orders#checkout", as: 'checkout'
  post "place_order" => "orders#place_order", as: 'place_order'

  #Section for singular checkout
  get "checkout_one" => "orders#checkout_one_restaurant", as: 'checkout_one_restaurant'
  post "place_order_one_restaurant" => "orders#place_order_one_restaurant", as: 'place_order_one_restaurant'


  get "dashboard" => "users#dashboard", as: 'dashboard'

  get "static_pages/home"

  get "past_orders/:unique_url" => "orders#guest_order_receipt", as: "past_orders"

  get "food/:food_type" => "restaurants#load_restaurants_by_type", as: "food_type"
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 3}
  validates :status, presence: true
  #validates :url_slug, presence: true, format: {with: /[A-Za-z0-9\-]+/, message: "Only use letters, numbers and -"}, uniqueness: {case_sensitive: false}
  validates :food_type, presence: true
  #before_save {|restaurant| restaurant.url_slug.downcase!}
  has_many :items
  has_many :order_items, through: :items
  has_many :restaurant_employees
  has_many :users, :through => :restaurant_employees
  has_one :restaurant_detail
  has_many :hours
  accepts_nested_attributes_for :restaurant_detail
  belongs_to :location
  has_many :order_restaurants
  has_many :orders, through: :order_restaurants

  def order_items_subtotal(items)
    items.inject(0) do |sum, order_item|
      item_price = Item.find(order_item.item_id).price
      sum + order_item.quantity * item_price
    end
  end

  def make_employee_admin(restaurant, employee)
    RestaurantEmployee.create(restaurant_id: restaurant.id, user_id: employee.id, admin: true)
  end

  def get_hours(restaurant)
    rid = restaurant.id
    Hours.where(restaurant_id: rid)
  end

  def food_style(style)
    where(food_type: style).where(status: "approved")
  end

  def open?
    Hours.where(closed:false).each do |hour|
      hour.restaurant
    end
  end

  def description
    if restaurant_detail
      return self.restaurant_detail.description
    end
  end

  def count
    where(:food_type => params[:food_type]).count
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :require_login, except: [:index, :show, :restaurant_admin, :load_restaurants_by_type]
  before_action :require_admin, only: [:approve]

  def index
    @restaurants = Restaurant.where(:status => "approved")
    @pending_restaurants = Restaurant.where(:status => "pending")
  end

  def new
    @restaurant = Restaurant.new
    @restaurant_detail = RestaurantDetail.new
    @hours = Hours.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @hours = Hours.new
    @restaurant_detail = RestaurantDetail.new(restaurant_detail_params)
    if @restaurant.save
      @restaurant.create_restaurant_detail(restaurant_detail_params)
      @hours.days.each do |day|
        hours_info = hours_params(day)
        @hours = Hours.new(hours_info)
        @hours.restaurant_id = @restaurant.id
        @hours.day = day
        @hours.save
      end
      redirect_to restaurants_path
      flash.notice = "#{@restaurant.name} was successfully created!"
      set_restaurant_admin
      RestaurantMailer.restaurant_created(current_user, @restaurant).deliver
      RestaurantMailer.restaurant_created_admin_notification(@restaurant).deliver
    else
      flash[:error] = "#{@restaurant.name} application was incomplete!"
      render 'new'
    end
  end

  def show
    @order = current_order
    @restaurant = Restaurant.find(params[:id])
    cookies[:restaurant_slug] = @restaurant.url_slug
    cookies[:restaurant_id] = @restaurant.id
    @items = @restaurant.items
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    if params[:restaurant][:status]
      @status = params[:restaurant][:status]
      @restaurant = Restaurant.find(params[:id])
      @restaurant.status = @status
      restaurant_admin = @restaurant.restaurant_employees.first
      @user = restaurant_admin.user
      @restaurant.save
      if @status == "approved"
        if @user
          RestaurantMailer.restaurant_approved(@user, @restaurant).deliver
        end
      else
        if @user
          RestaurantMailer.restaurant_denied(@user, @restaurant).deliver
        end
        @restaurant.destroy
      end
    else
      @restaurant = Restaurant.find(params[:id])
      @restaurant.update(restaurant_params)
    end
    redirect_to restaurants_path
  end

  def approve
    @restaurant = Restaurant.find(params[:id])
    @user = current_user
  end

  def restaurant_dashboard
    unless current_user.admin?
      @restaurant = current_user.restaurants.find(params[:id])
    else
      @restaurant = Restaurant.find(params[:id])
    end
    @restaurant_id = @restaurant.id
    @items = @restaurant.items
    @all_hours = @restaurant.get_hours(@restaurant)
    @hours = @all_hours.first
    @orders = @restaurant.orders.page(params[:page]).per(5)
  end

  def load_restaurants_by_type
    @restaurants = Restaurant.where(:food_type => params[:food_type]).page(params[:page]).per(10)
    filtered = Restaurant.where(:food_type => params[:food_type])
    @restaurants_count = filtered.count
  end

  private

  def update_status
    params.require(:restaurant).permit(:status)
  end

  def type_params
    params.require(:restaurant).permit(:food_type)
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :url_slug, :food_type)
  end

  def restaurant_detail_params
    params[:restaurant].require(:restaurant_detail).permit(:restuarant_id, :phone, :street, :street2, :city, :state, :zip, :description, :hours_id, :delivery, :delivery_range)
  end

  def hours_params(day)
    params[:restaurant].require(day.to_sym).permit(:restaurant_id, :start_at, :end_at, :closed)
  end

  def set_restaurant_admin
    admin = RestaurantEmployee.new
    admin.user_id = current_user.id
    admin.restaurant_id = @restaurant.id
    admin.admin = true
    admin.save
  end
end

app/views/restaurants/_employee_form.html.erb
<%= form_tag restaurant_employees_path, method: :post %>

<%= label_tag :email %>
<%= text_field_tag :email %>
<%= label_tag :role %>
<%= select_tag "role", options_for_select(%w(stocker admin)) %>
<%= hidden_field_tag :restaurant_id, @restaurant_id %> 
<%= submit_tag "HIRE!", :class => "btn btn-large btn-success" %>

app/views/restaurants/_form.html.erb
<h3>Required Details</h3>
<%= form_for @restaurant do |rest_form| %>
    <p>
      <%= rest_form.label :name %>
      <%= rest_form.text_field :name %>
    </p>
      <p>
      <%= rest_form.label :food_type %>
      <%= rest_form.text_field :food_type %>
    </p> 
    <br>
    <h3>Additional Details</h3>
  <%= rest_form.fields_for @restaurant_detail do |f| %>
      <p>
        <%= f.label :phone, "Phone" %>
        <%= f.text_field :phone %>
      </p>
      <p>
        <%= f.label :street, "Street Address" %>
        <%= f.text_field :street %>
      </p>
      <p>
        <%= f.label :street2, "Street Address Continued" %>
        <%= f.text_field :street2 %>
      </p>
      <p>
        <%= f.label :city, "City" %>
        <%= f.text_field :city %>
      </p>
      <p>
        <%= f.label :state, "State" %>
        <%= f.text_field :state %>
      </p>
      <p>
      <%= f.label :zip, "Zipcode" %> 
      <%= f.text_field :zip %>
      </p>
      <p>
        <%= f.label :description, "Description" %>
        <%= f.text_field :description %>
      </p>
    <p>
        <%= f.label :delivery, "Do You Deliver?" %> 
        <%= f.check_box :delivery %>
    </p>
    <p>
      <%= f.label :delivery_range, "Delivery Range (in miles)" %>
      <%= f.text_field :delivery_range %>
    </p>
  <% end %>
  <h3>Hours</h3>
  <% @hours.days.each do |day| %>
    <%= rest_form.fields_for day do |h| %>
       <h4><%= day %></h4>
       <%= h.hidden_field :day, :value => day %>
        <p>
          <%= h.label :closed, "Closed on #{day}?" %>
          <%= h.check_box :closed %>
        </p>
        <p>
          <%= h.label :start_at, "Opens" %>
          <%= h.time_select :start_at, {minute_step: 15, ampm: true} %>
        </p>
        <p>
          <%= h.label :end_at, "Closes" %>
          <%= h.time_select :end_at, {minute_step: 15, ampm: true} %>
        </p>
    <% end %>
  <% end %>
  <p>
    <br>
  <%= rest_form.submit "Apply for Restaurant Approval", :class => "btn btn-success" %>
  </p>
<% end %>

app/views/restaurants/_restaurant.html.erb
<h3 class="restaurant-<%= restaurant.id %>"> 
  <%= link_to restaurant.name, restaurant_path(restaurant)%> 
</h3>
<% if restaurant.restaurant_employees.any? %>
  <p> There is an employee <p>
<% end %>

app/views/restaurants/_restaurant_footer.html.erb
<nav>
  <br>
  <div class="container">

  </div>
</nav>

app/views/restaurants/_restaurant_header.html.erb
<nav>
  <div class="container">
    <h1><%= @restaurant.name %></h1>
    <% if @restaurant.restaurant_detail %>
      <h4><%= @restaurant.restaurant_detail.description %></h4>
    <% end %>
    <% if @restaurant.get_hours(@restaurant) %>
    Open:
    <br>
      |<% @restaurant.get_hours(@restaurant).each do |hour| %>
      <% if hour.closed == false %>
        <a href="#" class="btn btn-success btn-mini"><i class="icon-white icon-thumbs-up"></i></a>
      <% else %>
        <a href="#" class="btn btn-danger btn-mini"><i class="icon-white icon-thumbs-up"></i></a>
      <% end %>
      <%= hour.day %> |
      <% end %>
    <% end %>
  </div>
</nav>

app/views/restaurants/_restaurant_orders.html.erb
<h3> Total Orders for Your Restaurant</h3>
<%= @restaurant.order_restaurants.count %>
<br>
<br>
  <% if @orders.orders %>
    <% @orders.each do |order| %>
      <% if order.not_empty? %>
        <h3>Order Number: <%= order.id %> </h3>
        <p><strong>Date Placed:</strong> <%= order.updated_at.to_s(:long) %></p>
        <p><strong>User:</strong> <%= order.order_username(order.customer_id) %> </p>
        <h5>Order Status: <%= order.status %></h5>
          <table class="table">
            <thead>
              <tr>
                <td>Dish</td>
                <td>Description</td>
                <td>Price</td>
                <td>Quantity</td>
              </tr>
            </thead>
          <% order.items.each do |item| %>
            <tr>
              <% oi = OrderItem.where(order_id: order.id, item_id: item.id).first %>
              <td><%= link_to item.title, item_path(item.id) %></td>
              <td><%= item.description %></td>
              <td><%= print_price(item.price) %></td>
              <td> <%= oi.quantity %></td>
            </tr>
          <% end %>
          <tr>
            <td></td>
            <td><h4>Order Total:</h4></td>
            <td><h4><%= print_price(order.subtotal) %></h4></td>
            <td></td>
          </tr>
        </table>
        <hr>
      <% end %>
    <% end %>
  <% end %>
<%= paginate @orders %>

app/views/restaurants/_small_form.html.erb
<%= form_for @restaurant do |f| %>
<fieldset>
  <td>
    <tr>
<p>
<%= f.label      :name %>
<%= f.text_field :name %>
</p>
<p>  
<%= f.label :food_type %>
<%= f.text_field :food_type %>
</p>
</td>
</tr>

<%= f.submit :class => "btn-primary btn-large" %>
<% end %>
</fieldset>

app/views/restaurants/approve.html.erb
<h1><%= @restaurant.name %></h1>

<% if @restaurant.restaurant_detail %>
  <h4><%= @restaurant.restaurant_detail.description %></h4>
<% end %>

<% if @restaurant.get_hours(@restaurant) %>
  Open:
  <br>
  <% @restaurant.get_hours(@restaurant).each do |hour| %>
    <% if hour.closed == false %>
      <a href="#" class="btn btn-success btn-mini"><i class="icon-white icon-thumbs-up"></i></a>
    <% else %>
      <a href="#" class="btn btn-danger btn-mini"><i class="icon-white icon-thumbs-up"></i></a>
    <% end %>
    <%= hour.day %> |
  <% end %>
<% end %>
<% if @restaurant.restaurant_employees %>
  <h3>Current Employees</h3>
  <% @restaurant.restaurant_employees.each do |emp| %>
    <% if emp.user %>
        <%= emp.user.username %> 
    <% end %>
  <% end %>
<% end %>

<%= form_for @restaurant, :method => :put do |f| %>
    <%= f.hidden_field :status, :value => "approved" %> 
  <%= f.submit "Approve", :class => "btn btn-success" %>
<% end %>

<%= form_for @restaurant, :method => :put do |f| %>
    <%= f.hidden_field :status, :value => "denied" %> 
  <%= f.submit "Deny", :class => "btn btn-danger" %>
<% end %>

app/views/restaurants/index.html.erb
<h1> Active Restaurants </h1>
<div class="active-restaurants">
  <% @restaurants.each do |restaurant| %>
    <h3 class="restaurant-<%= restaurant.id %>"> 
      <%= link_to restaurant.name, restaurant_path(restaurant)%> 
    </h3>
  <% end %>
</div>

<div class="pending-restaurants">
<h1> Pending Restaurants </h1>
  <% @pending_restaurants.each do |restaurant| %>
    <h3 class="restaurant-<%= restaurant.id %>"> 
      <%= link_to restaurant.name, restaurant_path(restaurant)%> 
    </h3>
  <% end %>
</div>

app/views/restaurants/load_restaurants_by_type.html.erb
<div class="jumbotron">
  <h1>We have <%= @restaurants_count %> <%= @restaurants.first.food_type.capitalize %> Restaurants</h1>
  <p>Give one a try!</p>
</div>

<ul id="restaurant-types">
<% @restaurants.each do |restaurant| %>
    <li class="listing"> 
      <%= link_to restaurant.name, restaurant_path(restaurant)%>
      <%= restaurant.description  %>
    </li>
<% end %>
</ul>
<%= paginate @restaurants%>

app/views/restaurants/new.html.erb
<h1>Create a Restaurant</h1>

<%= render partial: "form" %>

app/views/restaurants/restaurant_dashboard.html.erb
<h1><%= link_to @restaurant.name, restaurant_path(@restaurant) %></h1>
<hr>

<h3> Edit Details </h3>
<%= render partial: 'small_form' %>
<hr>

 <h3>Current Employees</h3>
<% if @restaurant.restaurant_employees.count > 1 %>
  <% @restaurant.restaurant_employees.each do |emp| %>
  <% if emp.user %>
    <div class="employee<%= emp.user.username %>" >
      <%= emp.user.username %> 
      <%= link_to 'Fire', emp, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure you want to fire this person??' } %>
    </div>
  <% end %>
  <% end %>
<% end %>

<h3> Hire Employees </h3>
<%= render partial: "employee_form" %>

<hr>

<div class="menu-items">
  <h3>Menu Items</h3>
  <a id="menu-items"></a>
  <%= link_to "Create New Menu Item", new_item_path, {:class => "btn btn-success create-new-item"} %>
  <br>
  <br>
  <table>
  <% @items.each do |item| %>
    <tr>
      <td><%= link_to item.title, item_path(item.id) %></td>
      <td><%= link_to "Edit", edit_item_path(item.id), {:class => "btn btn-warning edit-item" } %></td>
      <td></td>
    </tr>
  <% end %>
  </table>
  <hr>
  <%= render partial: 'restaurant_orders' %>
</div>

app/views/restaurants/show.html.erb
<%= render 'restaurants/restaurant_header' %>
<div id="items">
<% cache @items do %>
  <ul>
    <% @items.each do |item| %>
    <li id="item_<%= item.id %>" class="item">
    <div class="item-wrapper">
    <% if item.image.exists? %>
      <%= image_tag item.image.url, {:class => "item-show-image"} %><br/>
    <% end %>
    <div class="item-details">
      <a href="<%= item_path item.id %>" class="title"><%= item.title %></a>
       <p> <%= item.description %></p>
       <p><%=print_price(item.price) %></p>
       <ul class="categories">
         <li class="glyphicon glyphicon-tag category"></li>
      <% cache item.categories do %>
         <% item.categories.each do |category| %>
         <li class="category"><%= link_to category.name, items_path(Categories: category.id) %></li>
          <% end %>
        </ul>
      <% end %>
        <%= button_to "Add to Order", add_item_path(item.id), {:class => "btn btn-success" } %>
    </div>
    </div>
    </li>
    <% end %>
<% end %>
  </ul>
</div>

<%= render 'restaurants/restaurant_footer' %>