config/routes.rb
DinnerDash::Application.routes.draw do

  resources :visitor_users

  resources :restaurants
  resources :items
  resources :orders
  resources :order_items
  resources :users
  resources :categories
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :charges
  resources :menus
  resources :hours
  resources :restaurant_employees
  resources :locations
  resources :order_restaurants
  root to: 'static_pages#home'

  get "orders/guest_checkout"

  get "approve/:id" => "restaurants#approve", as: 'approve'
  get "restaurant-dashboard/:id" => "restaurants#restaurant_dashboard", as: 'restaurant_dashboard'

  post "items/add_to_order/:id" => 'items#add_to_order', as: 'add_item'
  get "login" => "user_sessions#new"
  get "logout" => "user_sessions#destroy"

  get "checkout" => "orders#checkout", as: 'checkout'
  post "place_order" => "orders#place_order", as: 'place_order'

  #Section for singular checkout
  get "checkout_one" => "orders#checkout_one_restaurant", as: 'checkout_one_restaurant'
  post "place_order_one_restaurant" => "orders#place_order_one_restaurant", as: 'place_order_one_restaurant'


  get "dashboard" => "users#dashboard", as: 'dashboard'

  get "static_pages/home"

  get "past_orders/:unique_url" => "orders#guest_order_receipt", as: "past_orders"

  get "food/:food_type" => "restaurants#load_restaurants_by_type", as: "food_type"
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :order_items
  has_many :orders, through: :order_items
  has_many :categories, through: :item_categories
  has_many :item_categories
  belongs_to :restaurant, touch: true
  has_attached_file :image, bucket: 'platable'
  validates_presence_of :title, :description, :price
  validates_presence_of :restaurant_id

  def self.find_by_restaurant(restaurant_id)
    where(restaurant_id: restaurant_id)
  end

  def self.active
    where(active: true)
  end

  def update_categories(potential_categories)
    category_ids = potential_categories ? potential_categories.values : []
    self.categories = category_ids.collect { |id| Category.find(id) }
  end

  def self.add_item_or_update(order, item)
    if order.items.include? item
      order_item = OrderItem.where(order_id:order.id, item_id:item.id).first
      new_quantity = order_item.quantity + 1
      order_item.update(quantity: new_quantity)
    else
      order.items << item
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :require_login, except: [:index, :show, :add_to_order]
  before_action :require_admin, except: [:index, :show, :add_to_order]

  def index
    @order = current_order
    if params["Categories"]
      @category = Category.find(params["Categories"])
      @items = Item.active.find_all {|item| item.categories.include? @category}
    else
      @items = Item.active
    end
    @categories = Category.all
  end

  def new
    @item = Item.new
    @categories = Category.all
    unless current_user.admin?
      @restaurants = current_user.restaurants
    else
      @restaurants = Restaurant.all
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      @item.update_categories(params[:item][:category])
      redirect_to item_path(@item)
    else
      redirect_to user_path(current_user.id)
    end
  end

  def show
    @item = Item.find(params[:id])
    @order = current_order
  end

  def edit
    @item = Item.find(params[:id])
    @categories = Category.all
    unless current_user.admin?
      @restaurants = current_user.restaurants
    else
      @restaurants = Restaurant.all
    end
  end

  def update
    @item = Item.update(params[:id], item_params)
    @item.update_categories(params[:item][:category])
    redirect_to item_path(@item)
  end

  def add_to_order
    order = current_order
    item = Item.find(params[:id])
    Item.add_item_or_update(order, item)
    flash.notice = item.title + " added to cart!"
    redirect_to :back
  end

  private

  def item_params
    params.require(:item).permit(:title, :description, :price, :image, :active, :restaurant_id)
  end

end

app/views/items/_form.html.erb
<%= form_for(@item, html: {multipart: true}) do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </p>
  <br>
  <h4>Select a Category</h4>
  <% @categories.each do |category| %>
    <p class="category-checkbox">
    <%= check_box_tag "item[category][#{category.id}]", category.id, @item.categories.include?(category) %>
    <%= f.label category.name %>
    </p>
  <% end %>
  <br>
  <h4>Select a Restaurant</h4>
    <p class="restaurant-checkbox">
    <%= f.collection_select :restaurant_id, @restaurants, :id, :name  %>
    <%= f.label "Restaurant" %>
    </p>
  <br>
  <h4>Is this menu item active?</h4>
  <p class="active-checkbox">  <%= f.check_box :active %>
   <%= f.label :active, "Yes" %>
  </p>
  <br>
  <p>
    <% if @item.image.exists? %>
      <%= image_tag @item.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach an Image", :class => "item-image-label" %>
    <%= f.file_field :image, :class => "btn btn-default" %>
  </p>
  <p>
  <%= f.submit @item.new_record? ? "Add Item" : "Update item", :class => "btn btn-success" %>
  </p>
<% end %>

app/views/items/edit.html.erb
<%= render partial: 'form' %>

app/views/items/index.html.erb
<div class="select-menu">
	<%= form_tag("/items", method: "get", class:"select-category") do %>
  <% if @category %>
    <%= select_tag "Categories", options_from_collection_for_select(@categories, "id", "name", @category.id), {:class => "btn btn-default dropdown-toggle" }%>
  <% else %>
    <%= select_tag "Categories", options_from_collection_for_select(@categories, "id", "name"), {:class => "btn btn-default dropdown-toggle" }%>
  <% end %>
    <%= submit_tag "Browse by Category", {:class => "btn btn-info"} %>
	<% end %>	
    <%= link_to "View All", items_path, {:class => "btn btn-info view-all"} %>
</div>

<div id="items">
	<ul>
	  <% @items.each do |item| %>
	  <li id="item_<%= item.id %>" class="item">
    <div class="item-wrapper">
    <% if item.image.exists? %>
      <%= image_tag item.image.url, {:class => "item-show-image"} %><br/>
    <% end %>
    <div class="item-details">
      <a href="<%= item_path item.id %>" class="title"><%= item.title %></a>
       <p> <%= item.description %></p>
	     <p><%=print_price(item.price) %></p>
       <ul class="categories">
         <li class="glyphicon glyphicon-tag category"></li>
	       <% item.categories.each do |category| %>
         <li class="category"><%= link_to category.name, items_path(Categories: category.id) %></li>
     	    <% end %>
        </ul>
        <%= button_to "Add to Order", add_item_path(item.id), {:class => "btn btn-success" } %>
    </div>
    </div>
	  </li>
	  <% end %>
	</ul>
</div>

app/views/items/new.html.erb
<h1>Create an Item</h1>
<%= render partial: 'form' %>

app/views/items/show.html.erb
<% cache @item do %>
  <h2><%=	@item.title %></h2>
  <% if @item.image.exists? %>
    <%= image_tag @item.image.url, {:class => "item-show-image"} %>
      <% end %>
  <p><%= @item.description %></p>
  <p><%= print_price(@item.price) %></p>
  <ul class="categories">
    <li class="glyphicon glyphicon-tag category"></li>
    <% @item.categories.each do |category| %>
      <li class="category"><%= category.name %></li>
  	<% end %>
  </ul>
  <% end %>
  <% if @order %>
    <%= button_to "Add to Order", add_item_path(@item.id), {class: "btn btn-success"} %>
  <% else %>
    <%= link_to "Add to Order", new_order_path(:item_id => @item.id), {:class => "btn btn-success"} %>
  <% end %>