config/routes.rb
DinnerDash::Application.routes.draw do

  resources :visitor_users

  resources :restaurants
  resources :items
  resources :orders
  resources :order_items
  resources :users
  resources :categories
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :charges
  resources :menus
  resources :hours
  resources :restaurant_employees
  resources :locations
  resources :order_restaurants
  root to: 'static_pages#home'

  get "orders/guest_checkout"

  get "approve/:id" => "restaurants#approve", as: 'approve'
  get "restaurant-dashboard/:id" => "restaurants#restaurant_dashboard", as: 'restaurant_dashboard'

  post "items/add_to_order/:id" => 'items#add_to_order', as: 'add_item'
  get "login" => "user_sessions#new"
  get "logout" => "user_sessions#destroy"

  get "checkout" => "orders#checkout", as: 'checkout'
  post "place_order" => "orders#place_order", as: 'place_order'

  #Section for singular checkout
  get "checkout_one" => "orders#checkout_one_restaurant", as: 'checkout_one_restaurant'
  post "place_order_one_restaurant" => "orders#place_order_one_restaurant", as: 'place_order_one_restaurant'


  get "dashboard" => "users#dashboard", as: 'dashboard'

  get "static_pages/home"

  get "past_orders/:unique_url" => "orders#guest_order_receipt", as: "past_orders"

  get "food/:food_type" => "restaurants#load_restaurants_by_type", as: "food_type"
end

app/views/layouts/_footer.html.erb
<footer>
            <div class="container">
              <p>Craveyard. An open-source food ordering service built by gSchool class[1]</p>
              <p>Romeeka Gayhart, Persa Zula, &amp; Tyler Long</p>
            </div>
            <div id="Open A Restaurant"> 
              <% if current_user %>
                <p>Restaurant Owner? <%= link_to "Add Your Restaurant Now!", new_restaurant_path %></p>
              <% else %>
                <p>Restaurant Owner? <%= link_to "Sign Up Now!", new_user_path %></p>
              <% end %>
            </div>
          </footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Craveyard" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Craveyard" %>">
     <link href='http://fonts.googleapis.com/css?family=Merriweather+Sans:400,300,700,400italic' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", :media => "all" %>
   <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
          <a href="/" class="logo"><img src="/images/craveyard-chalk.png"></a>
          <div class="controls">

              <% if @order %>
                <%= link_to "My Order (#{@order.total_items})", order_path(@order.id), {:class => "btn btn-default"} %>
              <% end %>
            <%= link_to "Restaurants", root_path, {:class => "btn btn-primary"} %>
            <% if current_user %>
            <%= link_to "My Account", user_path(current_user), {:class => "btn btn-info"} %>
              <%= link_to "Logout", logout_path, {:class => "btn btn-warning"} %>
            <% else %>
              <%= link_to "Login", login_path, {:class => "btn btn-primary login"} %>
              <%= link_to "Sign Up", new_user_path, {:class => "btn btn-success sign-up"} %>
            <% end %>
          </div>
        <div class="container">
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <%= render 'layouts/footer' %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/platable.html.erb
<!DOCTYPE html>
<html>
 <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dinner Dash" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Dinner Dash" %>">
     <link href='http://fonts.googleapis.com/css?family=Merriweather+Sans:400,300,700,400italic' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", :media => "all" %>
   <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
          <a href="/" class="logo"><img src="/images/platable.png"></a>
          <div class="controls">
            <% if @order %>
              <%= link_to "My Order", order_path(@order.id), {:class => "btn btn-success"} %>
            <% end %>
            <% if current_user %>
            <%= link_to "My Account", user_path(current_user), {:class => "btn btn-info"} %>
              <%= link_to "Logout", logout_path, {:class => "btn btn-warning"} %>
            <% else %>
              <%= link_to "Login", login_path, {:class => "btn btn-primary login"} %>
            <% end %>
          </div>
        <div class="container">
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
            <div class="container">
              
            </div>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>